

[consumer]
STREAM_NAME = "TEST_MESSAGES"
GROUP_NAME = "TEST_GROUP"
NAME = "TEST_CONSUMER"
MESSAGE_BATCH_SIZE = 10

[producer]
STREAM_NAME = "TEST_MESSAGES"

[test]
PROCESS_TIME_MEAN = 1.6
PROCESS_TIME_VARIANCE = 0.2
PROCESS_FAILURE_CHANCE = 0
CONSUMER_PER_CYCLE_FAILUIRE_CHANCE = 0.01
