apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-consumer-processor-python
  namespace: test
spec:
  replicas: 10 # scale parameter
  selector:
    matchLabels:
      app: redis-consumer-processor-python
      servicename: api-billing-memo-document-consumer
  template:
    metadata:
      labels:
        app: redis-consumer-processor-python
        servicename: api-billing-memo-document-consumer
    spec:
      imagePullSecrets:
        - name: enerbit-registry
      containers:
        - name: redis-consumer-processor-python
          image: enerbit.azurecr.io/redis-consumer-processor-python:latest
          command: ["/bin/bash", "-c"]
          args: ["python main.py"]
          resources:
            requests:
              cpu: 10m
              memory: 120Mi
            limits:
              cpu: 200m
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: test-config
